fix(ADVISOR-3029): Fix Pathway details styling
RedHatInsights/insights-advisor-frontend pull request #1105
Opened 2023-04-07 21:06 UTC by adonispuente

# Description

Associated Jira ticket: # (ADVISOR-3029)
This PR reverts some styling issues that snuck-in in the removal of that <Main> component in this [PR](https://github.com/RedHatInsights/insights-advisor-frontend/pull/1066) 

# How to test the PR
Ensure the padding and colors look the same in a pathway details table as they do in other tables. 
Here is a picture before that PR for reference. 
<img width="1112" alt="Screen Shot 2023-04-07 at 5 05 32 PM" src="https://user-images.githubusercontent.com/60629070/230678852-3247ef7f-a2d9-4c29-9c62-cd09065a57e4.png">

# Before the change
![Screen Shot 2023-04-07 at 5 05 50 PM](https://user-images.githubusercontent.com/60629070/230678877-706dc38f-05e2-4458-8e46-a3c548e07a79.png)

# After the change
![Screen Shot 2023-04-07 at 5 06 12 PM](https://user-images.githubusercontent.com/60629070/230678919-ace11cfd-f30f-4bd5-9768-057df550ec5c.png)

# Dependent work link

# Checklist:

- [x] The commit message has the Jira ticket linked
- [x] PR has a short description
- [x] Screenshots before and after the change are added
- [ ] Tests for the changes have been added
- [ ] README.md is updated if necessary
- [ ] Needs additional dependent work

2023-04-11 07:30 UTC, mkholjuraev requested changes
The background color is fixed when a row is expanded, but I see the row width shrank than previous state. I believe this needs to be fixed:

![image](https://user-images.githubusercontent.com/59481011/231087918-01bbf677-0f4f-4ef1-9f6b-f92090906f3b.png)

2023-04-11 20:55 UTC, adonispuente commented
Good catch! I just sent up the changes @mkholjuraev

2023-04-20 19:31 UTC, adonispuente commented
@mkholjuraev just pinging this again

2023-04-21 06:57 UTC, mkholjuraev approved these changes
LGTM! The table looks good while shrinking, padding and colors are as expected. Thanks @adonispuente !

2023-04-24 13:50 UTC, merged