Update patternfly react-tokens
RedHatInsights/insights-advisor-frontend pull request #1232
Opened 2024-01-16 16:36 UTC by aneelac22

[RHINENG-6065](https://issues.redhat.com/browse/RHINENG-6065)

2024-01-16 17:17 UTC, dkuc approved these changes

2024-01-17 00:37 UTC, bastilian requested changes

2024-01-17 00:37 UTC, bastilian commented on package.json
> +    "@patternfly/react-tokens": "^5.1.2",
The v5 package may conflict with the v4 packages and we should refrain from mixing them.

2024-01-17 01:35 UTC, aneelac22 commented
I am actually closing this, I was trying to solve a specific chunk load error we were seeing in Fedramp but, we ended up reverting it back to when it was working to avoid instability for release tomorrow.

2024-01-17 01:35 UTC, closed without merging