add conditional filters to cypress tests
RedHatInsights/insights-advisor-frontend pull request #1315
Opened 2024-12-10 13:16 UTC by opacut

# Description

Associated Jira ticket: [RHINENG-14743](https://issues.redhat.com/browse/RHINENG-14743)

Add Conditional filter Cypress tests

# How to test the PR

run npm test:ct

# Before the change
90 tests are run

# After the change
At least 91 tests are run, including The Bulk selector shows the correct number of systems selected.

# Dependent work link

# Checklist:

- [ ] The commit message has the Jira ticket linked
- [ ] PR has a short description
- [ ] Screenshots before and after the change are added
- [ ] Tests for the changes have been added
- [ ] README.md is updated if necessary
- [ ] Needs additional dependent work

2025-01-06 21:48 UTC, johnsonm325 commented
@opacut your errors are for linting. `npm run lint` should give you everything you need.

2025-01-13 20:08 UTC, johnsonm325 requested changes
The [code climate](https://codeclimate.com/github/RedHatInsights/insights-advisor-frontend/pull/1315) bot is suggesting refactoring the following into a separate function. You could call an external helper function and pass in the value for `contains` and have it do these actions.

```
      cy.get(CONDITIONAL_FILTER_TOGGLE).click();
      cy.get(PT_CONDITIONAL_FILTER_LIST).contains('Name').click();
```

2025-01-17 14:37 UTC, johnsonm325 submitted a review, later dismissed

2025-01-20 14:46 UTC, LightOfHeaven1994 approved these changes
I have checked codeclimate and it's something that doesn't make much sense. I see code has been refactored for that and helper function is used. LGTM

2025-01-20 14:46 UTC, merged