Support Red Hat Disabled rules (aka autoack rules in the API)
RedHatInsights/insights-advisor-frontend pull request #755
Opened 2020-09-22 08:39 UTC by mhuth

Seems to work ok with the API changes in PR: https://github.com/RedHatInsights/insights-advisor-api/pull/642.  But they will need to go into prod together, otherwise :scream:

2020-09-22 08:46 UTC, mhuth commented
Showing all rules (using reports_shown === 'all' or just excluding the reports_shown parameter)
![all_rules_list](https://user-images.githubusercontent.com/4008744/93860829-fa572b00-fd02-11ea-9624-1e69fc92ef98.png)

Showing only the list of Red Hat Disabled rules:
![redhat_disabled_rule_list](https://user-images.githubusercontent.com/4008744/93860951-25417f00-fd03-11ea-8bc8-e63306bfd1ef.png)

Showing the Red Hat Disabled rule detail:
![redhat_disabled_rule_detail](https://user-images.githubusercontent.com/4008744/93861007-34c0c800-fd03-11ea-93ec-dade5969c657.png)

Note that enabling the rule worked correctly too.  Here's the Red Hat Disabled rule enabled again:
![Uploading enabling_redhat_disabled_rule.png…]()

2020-09-22 11:17 UTC, AllenBW commented on src/SmartComponents/Recs/List.js
> +let AdvisorRedHatDisabledRuleAlert = sessionStorage.getItem('AdvisorRedHatDisabledRuleAlert') || true;
OH GOOD I WAS WONDERING, cuz i got dinged last time for not having this 🤗🤗🤗🤗🤗

2020-09-22 11:20 UTC, AllenBW commented
@mhuth @dkuc is the api change needed for this breaking? or can it go to prod n we'll merge this whenever, no issues 🤔

2020-09-22 11:43 UTC, AllenBW requested changes
Just the one thing... OO no and another thing... be sure to run 

`npm run translations` so we get all them new stringzzzzzzzzzzzzzz captured n such 🤗 

LOOKS AWESOME OTHERWISE :AWESOME: 👍 🧑‍🏭

2020-09-22 11:43 UTC, AllenBW commented on src/SmartComponents/Recs/List.js
> +import { Alert } from '@patternfly/react-core/dist/js/components/Alert/Alert';
lets use the ems version of this, same for below

2020-09-22 12:55 UTC, mhuth commented
> @mhuth @dkuc is the api change needed for this breaking? or can it go to prod n we'll merge this whenever, no issues

@AllenBW The API change will break the frontend if they don't go into production together.  I guess I should change the API so it'll work with either version of the frontend, ie. using reports_shown=true or reports_shown=enabled.  I'll fix that up tomorrow ...

2020-09-23 11:22 UTC, terezanovotna commented
Looking good!
 - the inline notification should not spread across full screen - should be as in [mocks](https://marvelapp.com/prototype/e5gcj47/screen/71274223) or [here is documentation](https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/alerts-and-notifications)
- Red Hat disabled (no capitalization of D)

2020-09-24 06:41 UTC, mhuth commented
Going to close this in favour of PR https://github.com/RedHatInsights/insights-advisor-frontend/pull/757

2020-09-24 06:41 UTC, closed without merging