Use consistent page titles across Insights - add subapp name to page titles
RedHatInsights/insights-advisor-frontend pull request #780
Opened 2020-11-06 02:03 UTC by mhuth

Not sure if this is the right/react way of doing this.  Feedback is most welcome.

Old issue: https://issues.redhat.com/browse/ADVISOR-608
Mocks: https://marvelapp.com/prototype/e5gcj47/screen/71812909

Screenshots of changes:
![recommendations_title](https://user-images.githubusercontent.com/4008744/98317284-f0c22200-2027-11eb-90b8-98e0de6a42d8.png)
![systems_title](https://user-images.githubusercontent.com/4008744/98317306-f881c680-2027-11eb-9782-f6127561f520.png)
![topics_title](https://user-images.githubusercontent.com/4008744/98317321-fe77a780-2027-11eb-9815-f33181a708b2.png)

2020-11-06 13:31 UTC, AllenBW approved these changes
I like this! this is goooooodddddddd <3  nicely done @mhuth  🤗

2020-11-06 13:40 UTC, ryelo requested changes

2020-11-06 13:40 UTC, ryelo commented on src/Messages.js
> +        defaultMessage: 'Advisor {subapp} | Red Hat Insights'
This should actually be '{subapp} - Advisor | Red Hat Insights'

The `subapp` should also be capitalized. ex) `Topics - Advisor | Red Hat Insights`

2020-11-06 13:46 UTC, AllenBW requested changes
OK i still love this, but looks like we gotta go ah step further @mhuth https://docs.google.com/presentation/d/19voFhv_MUGwp-DNRj59mK_2YrignJLSWF9Jvbxk2bSU/edit#slide=id.g8e531b9fb1_0_0

need those detail pages to update the title as well, for example, from link above,`SAP - Topics - Advisor | Red Hat Insights`

2020-11-06 14:59 UTC, terezanovotna approved these changes

2020-11-06 15:00 UTC, terezanovotna commented
Looking good - fast turnaround on this!

2020-11-07 00:59 UTC, mhuth commented
Change page title to format `SubNav - Advisor | Red Hat Insights` and pre-pended topic names as required.

![topics](https://user-images.githubusercontent.com/4008744/98427260-29293500-20e8-11eb-856a-6e88fae1924c.png)
![sap_topic](https://user-images.githubusercontent.com/4008744/98427268-33e3ca00-20e8-11eb-893e-72059fb01f48.png)
![mssql_topic](https://user-images.githubusercontent.com/4008744/98427272-3cd49b80-20e8-11eb-9af8-8e4c64c82b27.png)

2020-11-09 11:42 UTC, AllenBW commented
Awesome quick additions! gotta wonder, doc says to mirror breadcrumbs... probably means we should also put rec details up there (the rec name)... wonder if that means we should put system name up there? (thinkin not, that gets long)

2020-11-10 01:45 UTC, mhuth commented
As per the breadcrumbs, I've prepended the rule description and system display_name to the document title.  The rule description can make the title very long.  The system display_name isn't too bad.  See screenshots ...

Reasonable rule description ...
![recs1](https://user-images.githubusercontent.com/4008744/98617081-f3838680-2349-11eb-9e51-f852c1c6d8e3.png)

Very long rule description ...
![recs2](https://user-images.githubusercontent.com/4008744/98617127-0dbd6480-234a-11eb-80dc-4953aaea454b.png)

System display_name ...
![systems1](https://user-images.githubusercontent.com/4008744/98617139-157d0900-234a-11eb-8e06-b03a634ab71a.png)

System display_name in
![systems2](https://user-images.githubusercontent.com/4008744/98617179-2b8ac980-234a-11eb-8863-b27ebb660ad6.png)
 document title from the recommendation system list ...

2020-11-10 12:23 UTC, AllenBW approved these changes
Looks good to me! nice work @mhuth 🤗 👍

2020-11-10 14:21 UTC, merged