Make RuleDetails fed module compatible with OCP rules
RedHatInsights/insights-advisor-frontend pull request #861
Opened 2021-08-16 18:51 UTC by gkarat

2021-08-16 19:04 UTC, AllenBW commented on src/PresentationalComponents/RuleDetails/RuleDetails.js
> +  const updateRuleRating = useCallback(
Hard no to this, there is a rule rating component already that does this work

2021-08-19 09:50 UTC, gkarat commented
@AllenBW, PTAL 👨🏼‍🔧 

I have tested it locally for RHEL Advisor. Everything works as expected except 403 error when trying to rate a rule (I have attached screenshots). But I suppose it is related to the local environment features, not to the PR's changes.

![Screenshot from 2021-08-19 11-48-02](https://user-images.githubusercontent.com/31385370/130047968-45fbe4be-bb72-4691-be44-9595d621a52e.png)
![Screenshot from 2021-08-19 11-47-50](https://user-images.githubusercontent.com/31385370/130047973-6c1270e8-7851-4b8a-aac5-ac82f68ce032.png)

2021-08-19 09:50 UTC, gkarat commented
For testing with OCP Advisor: well, there is no easy way to do it until we merge it... I will test it out as soon as you push it to fed modules :-)

2021-08-19 10:44 UTC, AllenBW commented on src/PresentationalComponents/RuleRating/RuleRating.js
> -import { injectIntl } from 'react-intl';
Swap this for use intl n instantiate it in the component rather than passing it in

2021-08-19 10:50 UTC, AllenBW requested changes
I get 403 on rule rating as well, gotta fix that before this can be merged ```You don't have permission to access "http://console.redhat.com/api/insights/v1/rating/" on this server.```

2021-08-20 16:16 UTC, AllenBW approved these changes
💯 🏅 🥅 :godmode: 

this stuff is da bomb, way to fix @gkarat <3

2021-08-20 16:17 UTC, merged