Advisor-2082: introduce application tour
RedHatInsights/insights-advisor-frontend pull request #890
Opened 2021-11-19 10:12 UTC by mkholjuraev

Application tour UI design is ready. The design includes a button with id='advisor_pendo_intro' that needs to binded with Pendo tour application. This will be done by  Margot Menestrot.  

![image](https://user-images.githubusercontent.com/59481011/142605473-f08fb248-cf75-4c94-ac28-0b6c5a656cbf.png)

2022-01-20 13:24 UTC, terezanovotna commented
Hi @mkholjuraev I don't see the button in prod, can we add it out there? the button will be then linked to this tour which is ready to go https://app.pendo.io/s/5300167311360000/guides/LR8rgW5-9fEM86HaWd2dWjT6vPU?view=settings

2022-01-20 13:32 UTC, terezanovotna commented
And as we do not have tours ready right now for the rest of the applications, let's cut the content under the button "Take Advisor tour"
<img width="201" alt="Screen Shot 2022-01-20 at 14 27 22" src="https://user-images.githubusercontent.com/36040135/150348188-6a6fa97a-c304-4337-a336-a2517a2c55f9.png"> and link the pendo tour to that button
.

2022-02-02 16:25 UTC, johnsonm325 requested changes
Everything seems good. Here's a suggested change.

2022-02-02 16:25 UTC, johnsonm325 commented on src/PresentationalComponents/AppIntro/AppIntro.js
> +      shouldClose={shouldClose}
You can remove `shouldClose` and `shouldOpen` functions in this component and simply pass `setShow` to the `shouldClose` and `shouldOpen` properties like so:
```
shouldClose={() => setShow(false)}
shouldOpen={() => setShow(true)}
```

2022-02-10 17:29 UTC, mkholjuraev commented
I do not like this asking a review after a rebase all the time :)

2022-02-14 15:47 UTC, jiridostal approved these changes

2022-02-15 08:42 UTC, merged