Advisor-2061: system details empty states are refactored
RedHatInsights/insights-advisor-frontend pull request #906
Opened 2022-02-16 10:37 UTC by mkholjuraev

Resolves: [Advisor](https://issues.redhat.com/browse/ADVISOR-2061).

To test:

1. Visit the system details page in Advisor application.
2. Filter the table to get empty state, check if everything is ok.
3. Open system details page with 0 recomendations, check if everything is ok.

2022-02-17 18:19 UTC, johnsonm325 commented
In case you don't know, you'll just need to remove two spaces per line in the EmptyStates.js file.

2022-02-17 20:03 UTC, johnsonm325 requested changes
I am having trouble testing this because I don't know how to get a system with no recommendations. If you can help me with that, then I can test this fully.

2022-02-17 21:12 UTC, johnsonm325 commented on src/SmartComponents/SystemAdvisor/SystemAdvisor.js
> -      );
Okay, I see the issue. `entity` is already defined as the system that all of the recommendations are related to. Here, a new variable named `entity` was set and it filters the rows.

Replace with something like this. It seems to work for me:
```
     const match = rows.find((row) => row?.rule?.rule_id === rule.rule_id);
     const selected = match?.selected;
     const isOpen = match?.isOpen || false;
```

2022-02-21 11:48 UTC, mkholjuraev commented on src/SmartComponents/SystemAdvisor/SystemAdvisor.js
> -      );
Nice catch. I have applied your changes and seems to work as expected.

2022-02-21 15:18 UTC, johnsonm325 approved these changes
Nice job!

2022-02-21 15:22 UTC, merged